// Generated by gencpp from file package/ImageProcessingRequest.msg
// DO NOT EDIT!


#ifndef PACKAGE_MESSAGE_IMAGEPROCESSINGREQUEST_H
#define PACKAGE_MESSAGE_IMAGEPROCESSINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package
{
template <class ContainerAllocator>
struct ImageProcessingRequest_
{
  typedef ImageProcessingRequest_<ContainerAllocator> Type;

  ImageProcessingRequest_()
    : angle(0.0)  {
    }
  ImageProcessingRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::package::ImageProcessingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package::ImageProcessingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ImageProcessingRequest_

typedef ::package::ImageProcessingRequest_<std::allocator<void> > ImageProcessingRequest;

typedef boost::shared_ptr< ::package::ImageProcessingRequest > ImageProcessingRequestPtr;
typedef boost::shared_ptr< ::package::ImageProcessingRequest const> ImageProcessingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package::ImageProcessingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package::ImageProcessingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package::ImageProcessingRequest_<ContainerAllocator1> & lhs, const ::package::ImageProcessingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package::ImageProcessingRequest_<ContainerAllocator1> & lhs, const ::package::ImageProcessingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package::ImageProcessingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package::ImageProcessingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package::ImageProcessingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package::ImageProcessingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package::ImageProcessingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package::ImageProcessingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package::ImageProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::package::ImageProcessingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d11dcdbe5a6f73dULL;
  static const uint64_t static_value2 = 0xd324353dc52315abULL;
};

template<class ContainerAllocator>
struct DataType< ::package::ImageProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package/ImageProcessingRequest";
  }

  static const char* value(const ::package::ImageProcessingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package::ImageProcessingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ImageProcessing.srv\n"
"float32 angle\n"
;
  }

  static const char* value(const ::package::ImageProcessingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package::ImageProcessingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageProcessingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package::ImageProcessingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package::ImageProcessingRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_MESSAGE_IMAGEPROCESSINGREQUEST_H
