// Generated by gencpp from file package/ImageProcessing.msg
// DO NOT EDIT!


#ifndef PACKAGE_MESSAGE_IMAGEPROCESSING_H
#define PACKAGE_MESSAGE_IMAGEPROCESSING_H

#include <ros/service_traits.h>


#include <package/ImageProcessingRequest.h>
#include <package/ImageProcessingResponse.h>


namespace package
{

struct ImageProcessing
{

typedef ImageProcessingRequest Request;
typedef ImageProcessingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageProcessing
} // namespace package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::package::ImageProcessing > {
  static const char* value()
  {
    return "e5775eef75e8eba6b10486d9b6b6d54e";
  }

  static const char* value(const ::package::ImageProcessing&) { return value(); }
};

template<>
struct DataType< ::package::ImageProcessing > {
  static const char* value()
  {
    return "package/ImageProcessing";
  }

  static const char* value(const ::package::ImageProcessing&) { return value(); }
};


// service_traits::MD5Sum< ::package::ImageProcessingRequest> should match
// service_traits::MD5Sum< ::package::ImageProcessing >
template<>
struct MD5Sum< ::package::ImageProcessingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::package::ImageProcessing >::value();
  }
  static const char* value(const ::package::ImageProcessingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::package::ImageProcessingRequest> should match
// service_traits::DataType< ::package::ImageProcessing >
template<>
struct DataType< ::package::ImageProcessingRequest>
{
  static const char* value()
  {
    return DataType< ::package::ImageProcessing >::value();
  }
  static const char* value(const ::package::ImageProcessingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::package::ImageProcessingResponse> should match
// service_traits::MD5Sum< ::package::ImageProcessing >
template<>
struct MD5Sum< ::package::ImageProcessingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::package::ImageProcessing >::value();
  }
  static const char* value(const ::package::ImageProcessingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::package::ImageProcessingResponse> should match
// service_traits::DataType< ::package::ImageProcessing >
template<>
struct DataType< ::package::ImageProcessingResponse>
{
  static const char* value()
  {
    return DataType< ::package::ImageProcessing >::value();
  }
  static const char* value(const ::package::ImageProcessingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACKAGE_MESSAGE_IMAGEPROCESSING_H
