// Generated by gencpp from file my_amr_pkg/sensorData.msg
// DO NOT EDIT!


#ifndef MY_AMR_PKG_MESSAGE_SENSORDATA_H
#define MY_AMR_PKG_MESSAGE_SENSORDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_amr_pkg
{
template <class ContainerAllocator>
struct sensorData_
{
  typedef sensorData_<ContainerAllocator> Type;

  sensorData_()
    : temperature(0.0)
    , humidity(0.0)  {
    }
  sensorData_(const ContainerAllocator& _alloc)
    : temperature(0.0)
    , humidity(0.0)  {
  (void)_alloc;
    }



   typedef float _temperature_type;
  _temperature_type temperature;

   typedef float _humidity_type;
  _humidity_type humidity;





  typedef boost::shared_ptr< ::my_amr_pkg::sensorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_amr_pkg::sensorData_<ContainerAllocator> const> ConstPtr;

}; // struct sensorData_

typedef ::my_amr_pkg::sensorData_<std::allocator<void> > sensorData;

typedef boost::shared_ptr< ::my_amr_pkg::sensorData > sensorDataPtr;
typedef boost::shared_ptr< ::my_amr_pkg::sensorData const> sensorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_amr_pkg::sensorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_amr_pkg::sensorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_amr_pkg::sensorData_<ContainerAllocator1> & lhs, const ::my_amr_pkg::sensorData_<ContainerAllocator2> & rhs)
{
  return lhs.temperature == rhs.temperature &&
    lhs.humidity == rhs.humidity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_amr_pkg::sensorData_<ContainerAllocator1> & lhs, const ::my_amr_pkg::sensorData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_amr_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_amr_pkg::sensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_amr_pkg::sensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_amr_pkg::sensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_amr_pkg::sensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_amr_pkg::sensorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_amr_pkg::sensorData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_amr_pkg::sensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2e8758e18c44f444f3fa51a1c5be723";
  }

  static const char* value(const ::my_amr_pkg::sensorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2e8758e18c44f44ULL;
  static const uint64_t static_value2 = 0x4f3fa51a1c5be723ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_amr_pkg::sensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_amr_pkg/sensorData";
  }

  static const char* value(const ::my_amr_pkg::sensorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_amr_pkg::sensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 temperature \n"
"float32 humidity \n"
;
  }

  static const char* value(const ::my_amr_pkg::sensorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_amr_pkg::sensorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temperature);
      stream.next(m.humidity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_amr_pkg::sensorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_amr_pkg::sensorData_<ContainerAllocator>& v)
  {
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    s << indent << "humidity: ";
    Printer<float>::stream(s, indent + "  ", v.humidity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_AMR_PKG_MESSAGE_SENSORDATA_H
