// Generated by gencpp from file server_project/CameraControl.msg
// DO NOT EDIT!


#ifndef SERVER_PROJECT_MESSAGE_CAMERACONTROL_H
#define SERVER_PROJECT_MESSAGE_CAMERACONTROL_H

#include <ros/service_traits.h>


#include <server_project/CameraControlRequest.h>
#include <server_project/CameraControlResponse.h>


namespace server_project
{

struct CameraControl
{

typedef CameraControlRequest Request;
typedef CameraControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraControl
} // namespace server_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_project::CameraControl > {
  static const char* value()
  {
    return "e5775eef75e8eba6b10486d9b6b6d54e";
  }

  static const char* value(const ::server_project::CameraControl&) { return value(); }
};

template<>
struct DataType< ::server_project::CameraControl > {
  static const char* value()
  {
    return "server_project/CameraControl";
  }

  static const char* value(const ::server_project::CameraControl&) { return value(); }
};


// service_traits::MD5Sum< ::server_project::CameraControlRequest> should match
// service_traits::MD5Sum< ::server_project::CameraControl >
template<>
struct MD5Sum< ::server_project::CameraControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_project::CameraControl >::value();
  }
  static const char* value(const ::server_project::CameraControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_project::CameraControlRequest> should match
// service_traits::DataType< ::server_project::CameraControl >
template<>
struct DataType< ::server_project::CameraControlRequest>
{
  static const char* value()
  {
    return DataType< ::server_project::CameraControl >::value();
  }
  static const char* value(const ::server_project::CameraControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_project::CameraControlResponse> should match
// service_traits::MD5Sum< ::server_project::CameraControl >
template<>
struct MD5Sum< ::server_project::CameraControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_project::CameraControl >::value();
  }
  static const char* value(const ::server_project::CameraControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_project::CameraControlResponse> should match
// service_traits::DataType< ::server_project::CameraControl >
template<>
struct DataType< ::server_project::CameraControlResponse>
{
  static const char* value()
  {
    return DataType< ::server_project::CameraControl >::value();
  }
  static const char* value(const ::server_project::CameraControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_PROJECT_MESSAGE_CAMERACONTROL_H
