// Generated by gencpp from file server_project/CameraControlRequest.msg
// DO NOT EDIT!


#ifndef SERVER_PROJECT_MESSAGE_CAMERACONTROLREQUEST_H
#define SERVER_PROJECT_MESSAGE_CAMERACONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server_project
{
template <class ContainerAllocator>
struct CameraControlRequest_
{
  typedef CameraControlRequest_<ContainerAllocator> Type;

  CameraControlRequest_()
    : angle(0.0)  {
    }
  CameraControlRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::server_project::CameraControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server_project::CameraControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraControlRequest_

typedef ::server_project::CameraControlRequest_<std::allocator<void> > CameraControlRequest;

typedef boost::shared_ptr< ::server_project::CameraControlRequest > CameraControlRequestPtr;
typedef boost::shared_ptr< ::server_project::CameraControlRequest const> CameraControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server_project::CameraControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server_project::CameraControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server_project::CameraControlRequest_<ContainerAllocator1> & lhs, const ::server_project::CameraControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server_project::CameraControlRequest_<ContainerAllocator1> & lhs, const ::server_project::CameraControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server_project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server_project::CameraControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_project::CameraControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_project::CameraControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_project::CameraControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_project::CameraControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_project::CameraControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server_project::CameraControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::server_project::CameraControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d11dcdbe5a6f73dULL;
  static const uint64_t static_value2 = 0xd324353dc52315abULL;
};

template<class ContainerAllocator>
struct DataType< ::server_project::CameraControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server_project/CameraControlRequest";
  }

  static const char* value(const ::server_project::CameraControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server_project::CameraControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# CameraControl.srv\n"
"float32 angle   # Requested camera angle\n"
;
  }

  static const char* value(const ::server_project::CameraControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server_project::CameraControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server_project::CameraControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server_project::CameraControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_PROJECT_MESSAGE_CAMERACONTROLREQUEST_H
