(cl:defpackage asho-msg
  (:use )
  (:export
   "<ACTIONNAMEACTION>"
   "ACTIONNAMEACTION"
   "<ACTIONNAMEACTIONFEEDBACK>"
   "ACTIONNAMEACTIONFEEDBACK"
   "<ACTIONNAMEACTIONGOAL>"
   "ACTIONNAMEACTIONGOAL"
   "<ACTIONNAMEACTIONRESULT>"
   "ACTIONNAMEACTIONRESULT"
   "<ACTIONNAMEFEEDBACK>"
   "ACTIONNAMEFEEDBACK"
   "<ACTIONNAMEGOAL>"
   "ACTIONNAMEGOAL"
   "<ACTIONNAMERESULT>"
   "ACTIONNAMERESULT"
  ))

