; Auto-generated. Do not edit!


(cl:in-package asho-msg)


;//! \htmlinclude ActionNameFeedback.msg.html

(cl:defclass <ActionNameFeedback> (roslisp-msg-protocol:ros-message)
  ((current_position
    :reader current_position
    :initarg :current_position
    :type cl:float
    :initform 0.0))
)

(cl:defclass ActionNameFeedback (<ActionNameFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionNameFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionNameFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name asho-msg:<ActionNameFeedback> is deprecated: use asho-msg:ActionNameFeedback instead.")))

(cl:ensure-generic-function 'current_position-val :lambda-list '(m))
(cl:defmethod current_position-val ((m <ActionNameFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader asho-msg:current_position-val is deprecated.  Use asho-msg:current_position instead.")
  (current_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionNameFeedback>) ostream)
  "Serializes a message object of type '<ActionNameFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_position))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionNameFeedback>) istream)
  "Deserializes a message object of type '<ActionNameFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_position) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionNameFeedback>)))
  "Returns string type for a message object of type '<ActionNameFeedback>"
  "asho/ActionNameFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionNameFeedback)))
  "Returns string type for a message object of type 'ActionNameFeedback"
  "asho/ActionNameFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionNameFeedback>)))
  "Returns md5sum for a message object of type '<ActionNameFeedback>"
  "a447468e6d196264c01d04f925289e8a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionNameFeedback)))
  "Returns md5sum for a message object of type 'ActionNameFeedback"
  "a447468e6d196264c01d04f925289e8a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionNameFeedback>)))
  "Returns full string definition for message of type '<ActionNameFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float32 current_position~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionNameFeedback)))
  "Returns full string definition for message of type 'ActionNameFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%float32 current_position~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionNameFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionNameFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionNameFeedback
    (cl:cons ':current_position (current_position msg))
))
