; Auto-generated. Do not edit!


(cl:in-package asho-msg)


;//! \htmlinclude ActionNameGoal.msg.html

(cl:defclass <ActionNameGoal> (roslisp-msg-protocol:ros-message)
  ((target_position
    :reader target_position
    :initarg :target_position
    :type cl:float
    :initform 0.0))
)

(cl:defclass ActionNameGoal (<ActionNameGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionNameGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionNameGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name asho-msg:<ActionNameGoal> is deprecated: use asho-msg:ActionNameGoal instead.")))

(cl:ensure-generic-function 'target_position-val :lambda-list '(m))
(cl:defmethod target_position-val ((m <ActionNameGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader asho-msg:target_position-val is deprecated.  Use asho-msg:target_position instead.")
  (target_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionNameGoal>) ostream)
  "Serializes a message object of type '<ActionNameGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'target_position))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionNameGoal>) istream)
  "Deserializes a message object of type '<ActionNameGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'target_position) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionNameGoal>)))
  "Returns string type for a message object of type '<ActionNameGoal>"
  "asho/ActionNameGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionNameGoal)))
  "Returns string type for a message object of type 'ActionNameGoal"
  "asho/ActionNameGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionNameGoal>)))
  "Returns md5sum for a message object of type '<ActionNameGoal>"
  "5425516b20f0095429537e35618ec273")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionNameGoal)))
  "Returns md5sum for a message object of type 'ActionNameGoal"
  "5425516b20f0095429537e35618ec273")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionNameGoal>)))
  "Returns full string definition for message of type '<ActionNameGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# ActionName.action~%~%# Goal~%float32 target_position~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionNameGoal)))
  "Returns full string definition for message of type 'ActionNameGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# ActionName.action~%~%# Goal~%float32 target_position~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionNameGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionNameGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionNameGoal
    (cl:cons ':target_position (target_position msg))
))
