// Generated by gencpp from file server_project/ImageRotation.msg
// DO NOT EDIT!


#ifndef SERVER_PROJECT_MESSAGE_IMAGEROTATION_H
#define SERVER_PROJECT_MESSAGE_IMAGEROTATION_H

#include <ros/service_traits.h>


#include <server_project/ImageRotationRequest.h>
#include <server_project/ImageRotationResponse.h>


namespace server_project
{

struct ImageRotation
{

typedef ImageRotationRequest Request;
typedef ImageRotationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImageRotation
} // namespace server_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_project::ImageRotation > {
  static const char* value()
  {
    return "9819b8903a9f0ce8015de560a2f07e7e";
  }

  static const char* value(const ::server_project::ImageRotation&) { return value(); }
};

template<>
struct DataType< ::server_project::ImageRotation > {
  static const char* value()
  {
    return "server_project/ImageRotation";
  }

  static const char* value(const ::server_project::ImageRotation&) { return value(); }
};


// service_traits::MD5Sum< ::server_project::ImageRotationRequest> should match
// service_traits::MD5Sum< ::server_project::ImageRotation >
template<>
struct MD5Sum< ::server_project::ImageRotationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_project::ImageRotation >::value();
  }
  static const char* value(const ::server_project::ImageRotationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_project::ImageRotationRequest> should match
// service_traits::DataType< ::server_project::ImageRotation >
template<>
struct DataType< ::server_project::ImageRotationRequest>
{
  static const char* value()
  {
    return DataType< ::server_project::ImageRotation >::value();
  }
  static const char* value(const ::server_project::ImageRotationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_project::ImageRotationResponse> should match
// service_traits::MD5Sum< ::server_project::ImageRotation >
template<>
struct MD5Sum< ::server_project::ImageRotationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_project::ImageRotation >::value();
  }
  static const char* value(const ::server_project::ImageRotationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_project::ImageRotationResponse> should match
// service_traits::DataType< ::server_project::ImageRotation >
template<>
struct DataType< ::server_project::ImageRotationResponse>
{
  static const char* value()
  {
    return DataType< ::server_project::ImageRotation >::value();
  }
  static const char* value(const ::server_project::ImageRotationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_PROJECT_MESSAGE_IMAGEROTATION_H
