// Generated by gencpp from file asho/ActionNameActionGoal.msg
// DO NOT EDIT!


#ifndef ASHO_MESSAGE_ACTIONNAMEACTIONGOAL_H
#define ASHO_MESSAGE_ACTIONNAMEACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <asho/ActionNameGoal.h>

namespace asho
{
template <class ContainerAllocator>
struct ActionNameActionGoal_
{
  typedef ActionNameActionGoal_<ContainerAllocator> Type;

  ActionNameActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  ActionNameActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::asho::ActionNameGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::asho::ActionNameActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asho::ActionNameActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ActionNameActionGoal_

typedef ::asho::ActionNameActionGoal_<std::allocator<void> > ActionNameActionGoal;

typedef boost::shared_ptr< ::asho::ActionNameActionGoal > ActionNameActionGoalPtr;
typedef boost::shared_ptr< ::asho::ActionNameActionGoal const> ActionNameActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asho::ActionNameActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asho::ActionNameActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::asho::ActionNameActionGoal_<ContainerAllocator1> & lhs, const ::asho::ActionNameActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::asho::ActionNameActionGoal_<ContainerAllocator1> & lhs, const ::asho::ActionNameActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace asho

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::asho::ActionNameActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asho::ActionNameActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asho::ActionNameActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asho::ActionNameActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asho::ActionNameActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asho::ActionNameActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asho::ActionNameActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10b9d081e0ca9f561ce811f0a88b9008";
  }

  static const char* value(const ::asho::ActionNameActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10b9d081e0ca9f56ULL;
  static const uint64_t static_value2 = 0x1ce811f0a88b9008ULL;
};

template<class ContainerAllocator>
struct DataType< ::asho::ActionNameActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asho/ActionNameActionGoal";
  }

  static const char* value(const ::asho::ActionNameActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asho::ActionNameActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ActionNameGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: asho/ActionNameGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# ActionName.action\n"
"\n"
"# Goal\n"
"float32 target_position\n"
"\n"
;
  }

  static const char* value(const ::asho::ActionNameActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asho::ActionNameActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionNameActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asho::ActionNameActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asho::ActionNameActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::asho::ActionNameGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASHO_MESSAGE_ACTIONNAMEACTIONGOAL_H
