// Generated by gencpp from file asho/ActionNameFeedback.msg
// DO NOT EDIT!


#ifndef ASHO_MESSAGE_ACTIONNAMEFEEDBACK_H
#define ASHO_MESSAGE_ACTIONNAMEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asho
{
template <class ContainerAllocator>
struct ActionNameFeedback_
{
  typedef ActionNameFeedback_<ContainerAllocator> Type;

  ActionNameFeedback_()
    : current_position(0.0)  {
    }
  ActionNameFeedback_(const ContainerAllocator& _alloc)
    : current_position(0.0)  {
  (void)_alloc;
    }



   typedef float _current_position_type;
  _current_position_type current_position;





  typedef boost::shared_ptr< ::asho::ActionNameFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asho::ActionNameFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ActionNameFeedback_

typedef ::asho::ActionNameFeedback_<std::allocator<void> > ActionNameFeedback;

typedef boost::shared_ptr< ::asho::ActionNameFeedback > ActionNameFeedbackPtr;
typedef boost::shared_ptr< ::asho::ActionNameFeedback const> ActionNameFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asho::ActionNameFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asho::ActionNameFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::asho::ActionNameFeedback_<ContainerAllocator1> & lhs, const ::asho::ActionNameFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_position == rhs.current_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::asho::ActionNameFeedback_<ContainerAllocator1> & lhs, const ::asho::ActionNameFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace asho

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::asho::ActionNameFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asho::ActionNameFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asho::ActionNameFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asho::ActionNameFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asho::ActionNameFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asho::ActionNameFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asho::ActionNameFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a447468e6d196264c01d04f925289e8a";
  }

  static const char* value(const ::asho::ActionNameFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa447468e6d196264ULL;
  static const uint64_t static_value2 = 0xc01d04f925289e8aULL;
};

template<class ContainerAllocator>
struct DataType< ::asho::ActionNameFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asho/ActionNameFeedback";
  }

  static const char* value(const ::asho::ActionNameFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asho::ActionNameFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float32 current_position\n"
"\n"
"\n"
;
  }

  static const char* value(const ::asho::ActionNameFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asho::ActionNameFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionNameFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asho::ActionNameFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asho::ActionNameFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_position: ";
    Printer<float>::stream(s, indent + "  ", v.current_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASHO_MESSAGE_ACTIONNAMEFEEDBACK_H
